### ISSUE TITLE
训练模型报错

### ISSUE THREAD

**Issue by hat-trick-msn** [open-mmlab/MMGEN-FaceStylor#10]
![Y5R@`WHIRDXU5GVXE~N~N7V](https://user-images.githubusercontent.com/55476762/164959551-c11ee364-95ec-48be-a1c2-7902ff30cdae.png)

**Comment by hat-trick-msn** [comment]
我用自己的数据集训练模型
!bash tools/dist_train.sh configs/agilegan/agile_transfer_photo2cartoon256x256_zplus_lpips0.5_freezeD5_ada_bs4x2_lr_2e-3_1600iter.py 1 --work-dir ./work_dirs/experiments/experiments_name

**Comment by hat-trick-msn** [comment]
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 157, in main
    meta=meta)
  File "/content/mmgeneration/mmgen/apis/train.py", line 208, in train_model
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/content/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 285, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/content/mmgeneration/mmgen/core/runners/dynamic_iterbased_runner.py", line 215, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/content/mmgeneration/mmgen/core/ddp_wrapper.py", line 123, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/content/MMGEN-FaceStylor/agilegan/transfer.py", line 414, in train_step
    loss_gen, log_vars_g, source_results = self._get_gen_loss(data_dict_)
  File "/content/MMGEN-FaceStylor/agilegan/transfer.py", line 121, in _get_gen_loss
    loss_ = loss_module(outputs_dict)
  File "/usr/local/lib/python3.7/dist-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/mmgeneration/mmgen/models/losses/gen_auxiliary_loss.py", line 261, in forward
    **kwargs)
  File "/content/mmgeneration/mmgen/models/losses/gen_auxiliary_loss.py", line 104, in gen_path_regularizer
    only_inputs=True)[0]
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/__init__.py", line 192, in grad
    inputs, allow_unused)
RuntimeError: module 'torch.backends.cudnn' has no attribute 'allow_tf32'
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-u', 'tools/train.py', '--local_rank=0', 'configs/agilegan/agile_transfer_photo2cartoon256x256_zplus_lpips0.5_freezeD5_ada_bs4x2_lr_2e-3_1600iter.py', '--launcher', 'pytorch', '--work-dir', './work_dirs/experiments/experiments_name']' returned non-zero exit status 1.

**Comment by zhysora** [comment]
您好，我也遇到了同样的报错，请问您解决了吗

**Comment by kfchenhn** [comment]
> 

+1

**Comment by xuguozhi** [comment]
+1
