### ISSUE TITLE
some questions about "Quick Try"

### ISSUE THREAD

**Issue by ssxxx1a** [open-mmlab/MMGEN-FaceStylor#15]
Hi,It's a great project! 
I have some questions about "Quick Try". I installed the whole process according to the "README", but when I run 'python demo/quick_try.py demo/src.png -- style toonify' I get the following problem:
```
Traceback (most recent call last):
  File "demo/quick_try.py", line 253, in <module>
    main()
  File "demo/quick_try.py", line 240, in main
    transfer_ckpt=os.path.join(args.ckpt_path, transfer_ckpt_name))
  File "demo/quick_try.py", line 118, in __init__
    device='cpu').eval()
  File "/home/abel/program/mmgeneration/mmgen/apis/inference.py", line 36, in init_model
    config.model, train_cfg=config.train_cfg, test_cfg=config.test_cfg)
  File "/home/abel/program/mmgeneration/mmgen/models/builder.py", line 32, in build_model
    return build(cfg, MODELS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/home/abel/program/mmgeneration/mmgen/models/builder.py", line 27, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/home/abel/anaconda3/envs/soul/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
urllib.error.URLError: <urlopen error PSPEncoderDecoder: <urlopen error [Errno 111] Connection refused>>
```
I finished in CUDA 10.2. 
What is the problem？

**Comment by chy0315** [comment]
I have also encountered the same problem. Have you resolved it？
