### ISSUE TITLE
ERROR: ADAStyleGAN2Discriminator is not in the module registry

### ISSUE THREAD

**Issue by yaofeng** [open-mmlab/MMGEN-FaceStylor#23]
```shell
python3 demo/quick_try.py demo/src.png --style toonify --save-path demo/src_output1.png
```
执行示例的时候报错，如何解决呢？
错误信息如下：
```
/workspace/ai-demo-python/open-mmlab/MMGEN-FaceStylor
Use vae style encoder
Loading ResNet ArcFace
load checkpoint from local path: work_dirs/pre-trained/agile_encoder_ffhq1024x1024_lr_1e-4_500kiter_20211201_112111-fb1312dc.pth
2023-02-17 02:57:14,225 - mmgen - INFO - Switch to evaluation style mode: single
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/workspace/ai-demo-python/open-mmlab/MMGEN-FaceStylor/agilegan/transfer.py", line 53, in __init__
    test_cfg=test_cfg)
  File "/opt/conda/lib/python3.7/site-packages/mmgen/models/gans/static_unconditional_gan.py", line 55, in __init__
    self.discriminator = build_module(discriminator)
  File "/opt/conda/lib/python3.7/site-packages/mmgen/models/builder.py", line 37, in build_module
    return build(cfg, MODULES, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmgen/models/builder.py", line 27, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'ADAStyleGAN2Discriminator is not in the module registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo/quick_try.py", line 252, in <module>
    main()
  File "demo/quick_try.py", line 239, in main
    transfer_ckpt=os.path.join(args.ckpt_path, transfer_ckpt_name))
  File "demo/quick_try.py", line 120, in __init__
    device='cpu').eval()
  File "/opt/conda/lib/python3.7/site-packages/mmgen/apis/inference.py", line 36, in init_model
    config.model, train_cfg=config.train_cfg, test_cfg=config.test_cfg)
  File "/opt/conda/lib/python3.7/site-packages/mmgen/models/builder.py", line 32, in build_model
    return build(cfg, MODELS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/opt/conda/lib/python3.7/site-packages/mmgen/models/builder.py", line 27, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/opt/conda/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "PSPTransfer: 'ADAStyleGAN2Discriminator is not in the module registry'"
/workspace/ai-demo-python/open-mmlab
```

**Comment by yaofeng** [comment]
使用如下版本依赖库，该问题可以解决：

**Comment by tmaobdr3353** [comment]
the same problem

**Comment by JustinBili** [comment]
I have also encountered the same problem. Have you resolved it？
